name: qbitconnect
description: "A Flutter app for managing qBittorrent remotely with a modern UI and real-time updates."
publish_to: 'none'
version: 1.5.1+24

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  file_picker: ^10.3.3
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  network_ninja: ^1.4.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  connectivity_plus: ^7.0.0
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_analytics: ^12.0.2
  path_provider: ^2.1.4
  app_links: ^6.3.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: false
  
  assets:
    - assets/translations/