name: qbitconnect
description: "A Flutter app for managing qBittorrent remotely with a modern UI and real-time updates."
publish_to: 'none'

version: 1.1.1+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  file_picker: ^10.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
  network_ninja: ^1.3.0
  url_launcher: ^6.3.1
  
  # Firebase packages (only essential ones)
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true