name: iOS-ipa-build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v1.0.0'

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Restore Firebase configuration files
        run: |
          echo "${{ secrets.FIREBASE_JSON_CONFIG }}" > firebase.json
          echo "${{ secrets.FIREBASE_OPTIONS_DART }}" > lib/firebase_options.dart
          echo "${{ secrets.IOS_FIREBASE_CONFIG }}" > ios/Runner/GoogleService-Info.plist

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Update CocoaPods repository
        run: pod repo update
        working-directory: ios

      - name: Disable FlutterFire upload script in iOS project files
        run: |
          set -e
          echo "Searching for 'flutterfire upload-crashlytics-symbols' under ios/..."
          matches=$(grep -R --line-number --exclude-dir=Pods "flutterfire upload-crashlytics-symbols" ios || true)
          if [ -n "$matches" ]; then
            echo "Found occurrences:"
            echo "$matches"
            # Replace occurrences with a harmless echo; create .bak backups for safety
            grep -R --files-with-matches --exclude-dir=Pods "flutterfire upload-crashlytics-symbols" ios | while read -r file; do
              echo "Patching $file"
              sed -i.bak 's#flutterfire upload-crashlytics-symbols#echo "CI: skipping flutterfire upload-crashlytics-symbols"#g' "$file"
            done
            echo "Patched files; backups created with .bak suffix."
          else
            echo "No occurrences found; nothing to patch."
          fi

      - name: Build Flutter framework and app (no codesign)
        run: flutter build ios --release --no-codesign || true

      - name: Build unsigned iOS app with xcodebuild
        run: |
          set -e
          # Basic unsigned build for device (Release-iphoneos)
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            clean build
        working-directory: ios

      - name: Create Payload directory and prepare IPA
        run: |
          set -e
          rm -rf Payload FlutterIpaExport.ipa
          mkdir -p Payload
          # Adjust path if your build output path differs
          cp -r ios/build/Release-iphoneos/Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FlutterIpaExport.ipa
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
          body: "Unsigned IPA for AltStore (CI build)."

